<?php
// $Id$

/**
 * @file
 * rel="logo" module file
 * 
 * This module implements the rel="logo" standard as described on 
 * http://relogo.org/.
 * rel="logo" is a proposed standard for serving and maintaining up-to-date 
 * logos for use in various media. By including a line of code on your site that
 * links to a scalable vector logo, you make it very easy for other websites, 
 * applications, readers, clients, and stations to ensure that they are using 
 * an approved logo directly from you.
 */

/**
 * Implement hook_help().
 */
function relogo_help($path, $arg) {
  if ($path == 'admin/help#relogo') {
    return t('rel="logo" is a proposed standard for serving and maintaining up-to-date logos for use in various media. By including a line of code on your site that links to a scalable vector logo, you make it very easy for other websites, applications, readers, clients, and stations to ensure that they are using an approved logo directly from you.');
  }
}

/**
 * Implement hook_menu().
 */
function relogo_menu() {
  $items = array();
  
  $items['admin/config/media/relogo'] = array(
    'title' => 'Relogo File',
    'description' => 'Configuration for the Relogo Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('relogo_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Form builder; Create and display the Relogo form for upload of file.
 */
function relogo_form($form, &$form_state) {
  // Enable the addition of the tag to the page.
  $form['relogo_enable'] = array(
    '#type' => 'checkbox',
    '#default_value' => variable_get('relogo_enable', FALSE),
    '#title' => t('Enable the tag'),
    '#description' => t('This will add a relogo link tag to the header on the site.'),
  );
  
  // Upload field for the file to be stored
  $form['relogo_upload_path'] = array(
    '#title' => t('Logo in svg'),
    '#type' => 'managed_file',
    '#description' => t('Logo file in svg to be exposed as a service.'),
    '#default_value' => variable_get('relogo_upload_path', ''),
    '#upload_location' => 'public://svg_logo/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('svg'),
    ),
  );
  
  $form = system_settings_form($form);
  
  $form['#submit'][] = 'relogo_form_submit';
  
  return $form;
}

/**
 * Save the file after it has been uploaded.
 */
function relogo_form_submit($form, &$form_state) {
  global $user;
  $account = $user;
  // Load the file via file.fid.
  if ($form_state['values']['relogo_upload_path']) {
    $file = file_load($form_state['values']['relogo_upload_path']);
    // Change status to permanent.
    $file->status = FILE_STATUS_PERMANENT;
    // Save.
    file_save($file);
    // Record that the module is using the file. 
    file_usage_add($file, 'relogo', 'user', $account->uid);
  }
}

/**
 * Implement hook_preprocess_html().
 */
function relogo_preprocess_html(&$variables) {
  if (variable_get('relogo_enable')) {
    $file = file_load(variable_get('relogo_upload_path'));
    drupal_add_html_head_link(array(
      'rel' => 'logo',
      'href' => file_create_url($file->uri),
      'type' => 'image/svg',
    ));
  }
}